<a href="https://colab.research.google.com/github/kittikhun62/efficientnet_keras_transfer_learning/blob/master/regression_test_2_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##เรียกใช้ CSV

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [23]:
import pandas as pd
import numpy as np

In [24]:
import os
%cd /content
if not os.path.isdir("efficientnet_keras_transfer_learning"):
 !git clone https://github.com/Wanita-8943/efficientnet_keras_transfer_learning
%cd efficientnet_keras_transfer_learning/

/content
/content/efficientnet_keras_transfer_learning


In [25]:
import sys
sys.path.append('/content/drive/My Drive/new/2Class_regression_freeze_1000.h5')

from efficientnet.layers import Swish, DropConnect
from efficientnet.model import ConvKernalInitializer
from tensorflow.keras.utils import get_custom_objects

get_custom_objects().update({
    'ConvKernalInitializer': ConvKernalInitializer,
    'Swish': Swish,
    'DropConnect':DropConnect
})

In [26]:
from tensorflow.keras.models import load_model
model = load_model('/content/drive/My Drive/new/2Class_regression_freeze_1000.h5')
height = width = model.input_shape[1]

In [27]:
df = pd.read_csv (f'/content/drive/My Drive/data - 2 class Regress.csv')
df

No                      Name_file  \
0      1                        pore-sb   
1      2                        pore-sb   
2      3                        pore-sb   
3      4                        pore-sb   
4      5                        pore-sb   
..   ...                            ...   
795  796  1-s2.0-S2095268622000210-main   
796  797  1-s2.0-S2095268622000210-main   
797  798  1-s2.0-S2095268622000210-main   
798  799  1-s2.0-S2095268622000210-main   
799  800  1-s2.0-S2095268622000210-main   

                                            Name_Paper  \
0    Preparation and electrochemical behaviour of b...   
1    Preparation and electrochemical behaviour of b...   
2    Preparation and electrochemical behaviour of b...   
3    Preparation and electrochemical behaviour of b...   
4    Preparation and electrochemical behaviour of b...   
..                                                 ...   
795  Integration of preparation of K, Na-embedded a...   
796  Integration of preparation of K, Na-embedded a...   
797  Integration of preparation of K, Na-embedded a...   
798  Integration of preparation of K, Na-embedded a...   
799  Integration of preparation of K, Na-embedded a...   

                                               journal  \
0                                  Korean J. Chem. Eng   
1                                  Korean J. Chem. Eng   
2                                  Korean J. Chem. Eng   
3                                  Korean J. Chem. Eng   
4                                  Korean J. Chem. Eng   
..                                                 ...   
795  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
796  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
797  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
798  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
799  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   

                                          path_Picture  detail  Class     BET  \
0    /content/drive/My Drive/new train/pore-sb/PCC(...   zoom1  0-800  135.06   
1    /content/drive/My Drive/new train/pore-sb/PCC(...   zoom2  0-800  135.06   
2    /content/drive/My Drive/new train/pore-sb/PCC(...   zoom3  0-800  135.06   
3    /content/drive/My Drive/new train/pore-sb/PCC(...   zoom4  0-800  135.06   
4    /content/drive/My Drive/new train/pore-sb/PCC(...   zoom5  0-800  135.06   
..                                                 ...     ...    ...     ...   
795  /content/drive/My Drive/new train/1-s2.0-S2095...  zoom21  0-800  301.70   
796  /content/drive/My Drive/new train/1-s2.0-S2095...  zoom22  0-800  301.70   
797  /content/drive/My Drive/new train/1-s2.0-S2095...  zoom23  0-800  301.70   
798  /content/drive/My Drive/new train/1-s2.0-S2095...  zoom24  0-800  301.70   
799  /content/drive/My Drive/new train/1-s2.0-S2095...  zoom25  0-800  301.70   

     Size(mico)  Class_01  
0            10         0  
1            10         0  
2            10         0  
3            10         0  
4            10         0  
..          ...       ...  
795          10         0  
796          10         0  
797          10         0  
798          10         0  
799          10         0  

[800 rows x 10 columns]

In [28]:
train = df[df['No'].between(1,598)]
test = df[df['No'].between(700,800)] 

In [29]:
DATA_PATH = "/content/drive/My Drive/new Regress"
os.chdir(DATA_PATH)
train_dir = os.path.join(DATA_PATH, 'train')
print(train_dir)
test_dir = os.path.join(DATA_PATH, 'test')
print(test_dir)

/content/drive/My Drive/new Regress/train
/content/drive/My Drive/new Regress/test


In [30]:
batch_size = 16

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
      rescale=1./255, #โมเดลส่วนใหญ่ต้องใช้ RGB ในช่วง 0–1
      rotation_range=40,
      width_shift_range=0.2,
      height_shift_range=0.2,
      shear_range=0.2,
      zoom_range=0.2,
      horizontal_flip=True,
      fill_mode='nearest')

# Note that the validation data should not be augmented!
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_dataframe(
        dataframe = train,
        directory = train_dir,
        x_col = 'path_Picture',
        y_col = 'Class_01',
        # รูปภาพทั้งหมดจะถูกปรับขนาดตามความสูงและความกว้างของเป้าหมาย
        target_size=(height, width),
        batch_size=batch_size,
        # Since we use categorical_crossentropy loss, we need categorical labels
        #เนื่องจากเราใช้ categorical_crossentropy loss เราจึงต้องมีป้ายกำกับตามหมวดหมู่
        class_mode = 'other')

#label
# labels = (train_generator.class_indices)
# labels = dict((v,k) for k,v in labels.items())
# print(labels)

Found 598 validated image filenames.


In [31]:
test = df[df['No'].between(700,800)]
test

No                      Name_file  \
699  700                     c9ra05225a   
700  701                      jp207232f   
701  702                      jp207232f   
702  703                      jp207232f   
703  704                      jp207232f   
..   ...                            ...   
795  796  1-s2.0-S2095268622000210-main   
796  797  1-s2.0-S2095268622000210-main   
797  798  1-s2.0-S2095268622000210-main   
798  799  1-s2.0-S2095268622000210-main   
799  800  1-s2.0-S2095268622000210-main   

                                            Name_Paper  \
699  Study of the pore structure and size effects o...   
700  Pore Size Effect of Carbon Electrodes on the E...   
701  Pore Size Effect of Carbon Electrodes on the E...   
702  Pore Size Effect of Carbon Electrodes on the E...   
703  Pore Size Effect of Carbon Electrodes on the E...   
..                                                 ...   
795  Integration of preparation of K, Na-embedded a...   
796  Integration of preparation of K, Na-embedded a...   
797  Integration of preparation of K, Na-embedded a...   
798  Integration of preparation of K, Na-embedded a...   
799  Integration of preparation of K, Na-embedded a...   

                                               journal  \
699                         ROYAL SOCIETY OF CHEMISTRY   
700  Renjie Chen, Zhouying He, Li Li, Feng Wu, Bin ...   
701  Renjie Chen, Zhouying He, Li Li, Feng Wu, Bin ...   
702  Renjie Chen, Zhouying He, Li Li, Feng Wu, Bin ...   
703  Renjie Chen, Zhouying He, Li Li, Feng Wu, Bin ...   
..                                                 ...   
795  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
796  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
797  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
798  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   
799  Dingzheng Wang,Deqing Zhu,Jian Pan, Zhengqi Gu...   

                                          path_Picture    detail     Class  \
699  /content/drive/My Drive/new train/c9ra05225a/m...  original  801-3200   
700  /content/drive/My Drive/new train/jp207232f/ME...     zoom1  801-3200   
701  /content/drive/My Drive/new train/jp207232f/ME...     zoom2  801-3200   
702  /content/drive/My Drive/new train/jp207232f/ME...     zoom3  801-3200   
703  /content/drive/My Drive/new train/jp207232f/ME...     zoom4  801-3200   
..                                                 ...       ...       ...   
795  /content/drive/My Drive/new train/1-s2.0-S2095...    zoom21     0-800   
796  /content/drive/My Drive/new train/1-s2.0-S2095...    zoom22     0-800   
797  /content/drive/My Drive/new train/1-s2.0-S2095...    zoom23     0-800   
798  /content/drive/My Drive/new train/1-s2.0-S2095...    zoom24     0-800   
799  /content/drive/My Drive/new train/1-s2.0-S2095...    zoom25     0-800   

        BET  Size(mico)  Class_01  
699  1980.0          10         1  
700  1467.0          10         1  
701  1467.0          10         1  
702  1467.0          10         1  
703  1467.0          10         1  
..      ...         ...       ...  
795   301.7          10         0  
796   301.7          10         0  
797   301.7          10         0  
798   301.7          10         0  
799   301.7          10         0  

[101 rows x 10 columns]

In [47]:
act = test['BET'].tolist() #ค่าจริง
path = test['path_Picture'].tolist() #path

In [48]:
from tensorflow.keras.preprocessing import image

def predict_image(img_path):
    # Read the image and resize it
    img = image.load_img(img_path, target_size=(height, width)) #รูปทุกรูปมีขนาดไม่เท่ากันจึงตั้งไว้ว่าเวลาจะให้ model ดึงรูปมาทำนายให้ดึงรูปเข้ามาตามขนาดที่ตั้งไว้ตามพารามิตเตอร์
    # Convert it to a Numpy array with target shape.
    x = image.img_to_array(img)  #model ไม่สามารถทำนายรูปภาพโดยตรงได้ จึงเเปลงรูปภาพให้เป็น array เเล้วให้โมเดลทำนาย
    # Reshape
    x = x.reshape((1,) + x.shape) # เพิ่ม ไดเมนชั่นของโมเดล ให้เป็น 4 ได้ เมนชั่น โดยที่ 1, คือบอกให้โมเดลนำเข้าทีละ 1 รูปเเล้วค่อยทำนาย เเละ + ไดเมนชั่น คือ 150 ,150 ,3(สีของ RGB)
    x /= 255.
    result = model.predict([x])
    return result[0]

In [49]:
predict_image(path[0])

1/1 [==============================] - 0s 87ms/step


array([994.57007], dtype=float32)

In [50]:
#Predict
pred_list = list()
prob_list = list()
img_path= path
for i in range(0,len(img_path)):
    predict = predict_image(img_path[i])
    result = predict[0]
    pred_list.append(result)
    # prob_list.append(predict[result])

1/1 [==============================] - 0s 30ms/step


In [63]:
predict

array([994.57007], dtype=float32)

In [62]:
result = predict[0]
result

994.57007

In [51]:
pred_list

[994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994.57007,
 994

In [52]:
print(type(pred_list))

<class 'list'>


In [53]:
pred_int = np.around(pred_list)

In [60]:
pred = np.array(pred_int) #แปลงเป็น array
act = np.array(act)

In [55]:
pred

array([995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995., 995., 995., 995., 995., 995., 995., 995., 995., 995.,
       995., 995.], dtype=float32)

In [58]:
import numpy as np
from sklearn.metrics import confusion_matrix

# act = test['BET'].array
# pred = test['path_Picture'].array

cmat = confusion_matrix(act, pred)
print('classifier accuracy = {}%'.format((100.*np.trace(cmat))/(np.sum(cmat))))

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(act, pred))#performance

ValueError: ignored

In [ ]:
#create CF 
data = {'Actual': act,'Predicted' : pred}
df = pd.DataFrame(data, columns=['Actual','Predicted'])
conf_mat = pd.crosstab(df['Actual'],df['Predicted'],rownames=['Actual'],colnames=['Predicted'])

#Confusion matrix
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
cm = confusion_matrix(act, pred)

#plot Confusion matrix
import seaborn as sns
sns.set()
fig, ax = plt.subplots(figsize=(10, 10))

ax = sns.heatmap(conf_mat, annot=True, fmt="d", cmap="YlGnBu") #Blues,Oranges,Reds
ax.set_title('Confusion matrix',fontsize=20)
ax.set_ylabel('True label',fontsize=18)
ax.set_xlabel('Predicted label',fontsize=18)